[project]
name = "minimum-reproduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "temporalio>=1.10.0",
]
[dependency-groups]
dev = [
    'pytest>=7.0.0',
    'pytest-asyncio>=0.18.0',
]
